GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzEwMjE2MDIzLCJleHAiOjE3MTA0NzUyMjN9.emvyjZNqKVQr4ji9iBHS5NyKIHQblhPMeEWtB3xkWbA

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzEwMjE1Mjc5fQ.DXCo7fJLBC5i4GePbqL1dDEQ7YODfzUpPzD1ePqEZLk"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzEwMjE2MDIzfQ.edJ_m3bMUTHySkWFfIuEKyhiDCinvZBq2Q3TZxMM5Yg"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Jim"
}